apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc3
  namespace: wordpress-ha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  volumeName: pv-mysql3  # <-- référence le PV

