apiVersion: v1
kind: Service
metadata:
  name: mysql # C'est le nom d'hôte pour WordPress
  namespace: wordpress-ha
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None # Headless pour la stabilité DNS interne
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wordpress-ha
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0 # Plus stable pour WP que la 8.1
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "esgi"
        - name: MYSQL_DATABASE
          value: "wordpress"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc-final
