apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql3
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.1.10.66
    path: /srv/nfs/k8s/mysql
---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv-wordpress
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: nfs
#  nfs:
#    server: 10.1.10.66
#    path: /srv/nfs/k8s/wordpress

